//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErdaldanisEDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitmenEkle
    {
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string bolum { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int egitmenId { get; set; }
        public string fakulte { get; set; }
    }
}
